version: '3.2'
services:
    nginx:
        build: docker/nginx
        ports:
            - 8080:80
            - 8082:443
        restart: always
        container_name: test_nginx
        extra_hosts:
            - "test-task.loc:127.0.0.1"
        domainname: test-task.loc
        environment:
            VIRTUAL_HOST: test-task.loc
        volumes:
            - ~/var/www:/var/www:ro
        networks:
            - back-tier
    php:
        build: docker/php
        restart: always
        container_name: test_php
        volumes:
            - ./:/var/www
        networks:
            - front-tier
            - back-tier
    mysql:
        build: docker/db
        restart: always
        container_name: test_db
        env_file:
            - ".env"
        volumes:
            - mysql:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - "3306:3306"
        networks:
            - back-tier

volumes:
    mysql:
        driver: local

networks:
    back-tier:
      driver: bridge